//! Components for constructing HTTP applications.

pub mod fallback;
pub mod route;

mod builder;
mod error;
pub(crate) mod imp;
mod mount;
mod router;
mod uri;

#[cfg(test)]
mod tests;

use self::uri::Uri;
pub use self::{
    builder::{Builder, Scope},
    error::{Error, Result},
    mount::{mount, Mount},
};
use {
    self::router::Router,
    crate::{common::TryFrom, error::Critical, input::RequestBody, output::ResponseBody},
    futures01::{Async, Poll},
    http::{Request, Response},
    std::sync::Arc,
    tower_service::{NewService, Service},
};

/// The main type which represents an HTTP application.
#[derive(Debug, Clone)]
pub struct App {
    inner: Arc<AppInner>,
}

#[derive(Debug)]
struct AppInner {
    router: Router,
}

impl App {
    /// Create a `Builder` to configure the instance of `App`.
    pub fn builder() -> Builder<()> {
        Builder::default()
    }

    /// Create a `Builder` with the specified prefix.
    pub fn with_prefix<T>(prefix: T) -> Result<Builder<()>>
    where
        Uri: TryFrom<T>,
    {
        Ok(Self::builder().prefix(Uri::try_from(prefix)?))
    }
}

impl NewService for App {
    type Request = Request<RequestBody>;
    type Response = Response<ResponseBody>;
    type Error = Critical;
    type Service = AppService;
    type InitError = Critical;
    type Future = futures01::future::FutureResult<Self::Service, Self::InitError>;

    fn new_service(&self) -> Self::Future {
        futures01::future::ok(AppService {
            inner: self.inner.clone(),
        })
    }
}

/// The instance of `Service` generated by `App`.
#[derive(Debug)]
pub struct AppService {
    inner: Arc<AppInner>,
}

impl Service for AppService {
    type Request = Request<RequestBody>;
    type Response = Response<ResponseBody>;
    type Error = Critical;
    type Future = self::imp::AppFuture;

    #[inline]
    fn poll_ready(&mut self) -> Poll<(), Self::Error> {
        Ok(Async::Ready(()))
    }

    #[inline]
    fn call(&mut self, request: Self::Request) -> Self::Future {
        self::imp::AppFuture::new(request, self.inner.clone())
    }
}
