(function() {var implementors = {};
implementors["tsukuyomi"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tsukuyomi/fs/struct.OpenConfig.html\" title=\"struct tsukuyomi::fs::OpenConfig\">OpenConfig</a>",synthetic:false,types:["tsukuyomi::fs::OpenConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tsukuyomi/input/localmap/struct.LocalMap.html\" title=\"struct tsukuyomi::input::localmap::LocalMap\">LocalMap</a>",synthetic:false,types:["tsukuyomi::input::localmap::LocalMap"]},];
implementors["tsukuyomi_askama"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tsukuyomi_askama/struct.Renderer.html\" title=\"struct tsukuyomi_askama::Renderer\">Renderer</a>",synthetic:false,types:["tsukuyomi_askama::Renderer"]},];
implementors["tsukuyomi_cors"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tsukuyomi_cors/struct.Builder.html\" title=\"struct tsukuyomi_cors::Builder\">Builder</a>",synthetic:false,types:["tsukuyomi_cors::Builder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tsukuyomi_cors/struct.CORS.html\" title=\"struct tsukuyomi_cors::CORS\">CORS</a>",synthetic:false,types:["tsukuyomi_cors::CORS"]},];
implementors["tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tungstenite/protocol/frame/struct.FrameHeader.html\" title=\"struct tungstenite::protocol::frame::FrameHeader\">FrameHeader</a>",synthetic:false,types:["tungstenite::protocol::frame::frame::FrameHeader"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tungstenite/protocol/struct.WebSocketConfig.html\" title=\"struct tungstenite::protocol::WebSocketConfig\">WebSocketConfig</a>",synthetic:false,types:["tungstenite::protocol::WebSocketConfig"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
