[package]
name = "example-template-askama"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_template_askama"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { path = "../../tsukuyomi" }
tsukuyomi-askama = { path = "../../tsukuyomi-askama" }
askama = "0.7.2"
exitfailure = "0.5"
