#!/bin/bash

set -e

[[ -n "${DISABLE_GIT_HOOKS}" ]] && {
    echo "[warn] Git hooks are disabled by user."
    exit 0
}

if cargo fmt --version >/dev/null 2>&1; then
    (set -x; cargo fmt -- --check)
fi

if cargo version-sync --version >/dev/null 2>&1; then
    (set -x; cargo version-sync --check)
fi
