#!/bin/bash

set -e

[[ -n "${DISABLE_GIT_HOOKS}" ]] && {
    echo "[warn] Git hooks are disabled by user."
    exit 0
}

BRANCH="$(git symbolic-ref --short HEAD)"
[[ "${BRANCH:-}" = wip-* ]] && {
    echo "[info] The current branch is working in progress."
    exit 0
}

[[ -z $(git status --porcelain) ]] || {
    echo '[error] The repository is dirty.'
    exit 1
}

set -x
exec "$(git rev-parse --show-toplevel)/.ci/run_test.sh"
