(function() {var implementors = {};
implementors["tsukuyomi"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"tsukuyomi/util/enum.Never.html\" title=\"enum tsukuyomi::util::Never\">Never</a>",synthetic:false,types:["tsukuyomi::util::Never"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"tsukuyomi/app/config/struct.Error.html\" title=\"struct tsukuyomi::app::config::Error\">Error</a>",synthetic:false,types:["tsukuyomi::app::config::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"tsukuyomi/input/body/struct.Error.html\" title=\"struct tsukuyomi::input::body::Error\">Error</a>",synthetic:false,types:["tsukuyomi::input::body::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"tsukuyomi/test/struct.AssertionError.html\" title=\"struct tsukuyomi::test::AssertionError\">AssertionError</a>",synthetic:false,types:["tsukuyomi::test::AssertionError"]},];
implementors["tsukuyomi_tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"tsukuyomi_tungstenite/struct.StreamError.html\" title=\"struct tsukuyomi_tungstenite::StreamError\">StreamError</a>",synthetic:false,types:["tsukuyomi_tungstenite::ws::StreamError"]},];
implementors["tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"tungstenite/error/enum.Error.html\" title=\"enum tungstenite::error::Error\">Error</a>",synthetic:false,types:["tungstenite::error::Error"]},{text:"impl&lt;Role:&nbsp;<a class=\"trait\" href=\"tungstenite/handshake/trait.HandshakeRole.html\" title=\"trait tungstenite::handshake::HandshakeRole\">HandshakeRole</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"tungstenite/handshake/enum.HandshakeError.html\" title=\"enum tungstenite::handshake::HandshakeError\">HandshakeError</a>&lt;Role&gt;",synthetic:false,types:["tungstenite::handshake::HandshakeError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
