(function() {var implementors = {};
implementors["juniper"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juniper/parser/enum.ScalarToken.html\" title=\"enum juniper::parser::ScalarToken\">ScalarToken</a>&lt;'a&gt;",synthetic:false,types:["juniper::parser::lexer::ScalarToken"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juniper/parser/enum.Token.html\" title=\"enum juniper::parser::Token\">Token</a>&lt;'a&gt;",synthetic:false,types:["juniper::parser::lexer::Token"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"juniper/parser/struct.SourcePosition.html\" title=\"struct juniper::parser::SourcePosition\">SourcePosition</a>",synthetic:false,types:["juniper::parser::utils::SourcePosition"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"juniper/parser/struct.Spanning.html\" title=\"struct juniper::parser::Spanning\">Spanning</a>&lt;T&gt;",synthetic:false,types:["juniper::parser::utils::Spanning"]},];
implementors["tsukuyomi"] = [{text:"impl&lt;L:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>, R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tsukuyomi/util/enum.Either.html\" title=\"enum tsukuyomi::util::Either\">Either</a>&lt;L, R&gt;",synthetic:false,types:["tsukuyomi::util::Either"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tsukuyomi/output/struct.ResponderFn.html\" title=\"struct tsukuyomi::output::ResponderFn\">ResponderFn</a>&lt;R&gt;",synthetic:false,types:["tsukuyomi::output::ResponderFn"]},{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tsukuyomi/output/struct.Oneshot.html\" title=\"struct tsukuyomi::output::Oneshot\">Oneshot</a>&lt;F&gt;",synthetic:false,types:["tsukuyomi::output::Oneshot"]},];
implementors["tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.OpCode.html\" title=\"enum tungstenite::protocol::frame::coding::OpCode\">OpCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::OpCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.Data.html\" title=\"enum tungstenite::protocol::frame::coding::Data\">Data</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::Data"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.Control.html\" title=\"enum tungstenite::protocol::frame::coding::Control\">Control</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::Control"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.CloseCode.html\" title=\"enum tungstenite::protocol::frame::coding::CloseCode\">CloseCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::CloseCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/enum.Role.html\" title=\"enum tungstenite::protocol::Role\">Role</a>",synthetic:false,types:["tungstenite::protocol::Role"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tungstenite/protocol/struct.WebSocketConfig.html\" title=\"struct tungstenite::protocol::WebSocketConfig\">WebSocketConfig</a>",synthetic:false,types:["tungstenite::protocol::WebSocketConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tungstenite/handshake/server/struct.NoCallback.html\" title=\"struct tungstenite::handshake::server::NoCallback\">NoCallback</a>",synthetic:false,types:["tungstenite::handshake::server::NoCallback"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/stream/enum.Mode.html\" title=\"enum tungstenite::stream::Mode\">Mode</a>",synthetic:false,types:["tungstenite::stream::Mode"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
