(function() {var implementors = {};
implementors["tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.OpCode.html\" title=\"enum tungstenite::protocol::frame::coding::OpCode\">OpCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::OpCode"]},{text:"impl&lt;'t&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for &amp;'t <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.CloseCode.html\" title=\"enum tungstenite::protocol::frame::coding::CloseCode\">CloseCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::CloseCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.CloseCode.html\" title=\"enum tungstenite::protocol::frame::coding::CloseCode\">CloseCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::CloseCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt;&gt; for <a class=\"enum\" href=\"tungstenite/enum.Message.html\" title=\"enum tungstenite::Message\">Message</a>",synthetic:false,types:["tungstenite::protocol::message::Message"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
