[package]
name = "tsukuyomi-askama-macros"
version = "0.1.0" # <cargo-version-sync>
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
