[package]
name = "example-websocket"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "websocket"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { version = "0.3.0-dev", features = ["websocket"] }
futures = "0.1.21"
