[package]
name = "tsukuyomi-core"
version = "0.4.0-dev" # <cargo-version-sync>
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
build = "build.rs"
publish = false

[dependencies]
bytes = "0.4"
cookie = { version = "0.11", features = ["percent-encode"] }
either = "1.5"
failure = "0.1.2"
futures = "0.1"
http = "0.1"
indexmap = "1"
log = "0.4"
mime = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "0.3"
serde_urlencoded = "0.5"
tower-service = "0.1"
url = "1.7.1"
uuid = "0.7.1"

[dependencies.tsukuyomi-server]
version = "0.4.0-dev" # <cargo-version-sync>
path = "../server"

[dependencies.tsukuyomi-macros]
version = "0.4.0-dev" # <cargo-version-sync>
path = "../macros"

[dev-dependencies]
matches = "0.1"
cargo-version-sync = { git = "https://github.com/ubnt-intrepid/cargo-version-sync.git", default-features = false }

[dev-dependencies.tsukuyomi]
version = "0.4.0-dev" # <cargo-version-sync>
path = ".."

[features]
secure = ["cookie/secure"]
