//! Components for the basic mechanisim for HTTP/1.1 server upgrade.
//!
//! # Examples
//!
//! ```
//! # extern crate tsukuyomi;
//! # extern crate futures;
//! # extern crate http;
//! # use tsukuyomi::error::Error;
//! # use tsukuyomi::input::Input;
//! # use tsukuyomi::input::upgrade::{Upgraded};
//! # use tsukuyomi::output::{Output, ResponseBody};
//! # use futures::{future, Future};
//! # use http::{header, StatusCode, Response};
//! # #[allow(unused_variables, dead_code)]
//! fn validate(input: &Input) -> Result<(), Error> {
//!     // do some stuff ...
//! #   Ok(())
//! }
//!
//! # #[allow(unused_variables, dead_code)]
//! fn on_upgrade(io: Upgraded)
//!     -> impl Future<Item = (), Error = ()> + Send + 'static {
//!     // ...
//! #   future::ok(())
//! }
//!
//! # #[allow(dead_code)]
//! fn handshake(input: &mut Input) -> Result<Output, Error> {
//!     validate(input)?;
//!
//!     // Register a callback function called when upgrading
//!     // the server protocol.
//!     let _ = input.body_mut().on_upgrade(on_upgrade);
//!
//!     // Build the handshake response.
//!     // If the status code is set to `101 Switching Protocols`,
//!     // a task will be generated by calling a callback function
//!     // registered at the above section at the end of handling
//!     // the request.
//!     Ok(Response::builder()
//!         .status(StatusCode::SWITCHING_PROTOCOLS)
//!         .header(header::UPGRADE, "foo")
//!         .body(ResponseBody::empty())
//!         .unwrap())
//! }
//! ```

use futures::{Future, IntoFuture};
pub use hyper::upgrade::Upgraded;

/// A trait representing a function called at performing the protocol upgrade.
pub trait OnUpgrade: Send + 'static {
    /// Creates a task for processing the upgraded protocol from the specified context.
    fn on_upgrade(self, io: Upgraded) -> Box<dyn Future<Item = (), Error = ()> + Send + 'static>;
}

impl<F, R> OnUpgrade for F
where
    F: FnOnce(Upgraded) -> R + Send + 'static,
    R: IntoFuture<Item = (), Error = ()>,
    R::Future: Send + 'static,
{
    fn on_upgrade(self, io: Upgraded) -> Box<dyn Future<Item = (), Error = ()> + Send + 'static> {
        Box::new((self)(io).into_future())
    }
}

#[cfg_attr(feature = "cargo-clippy", allow(type_complexity))]
pub(crate) struct OnUpgradeObj(
    Box<dyn FnMut(Upgraded) -> Box<dyn Future<Item = (), Error = ()> + Send> + Send + 'static>,
);

impl OnUpgradeObj {
    pub(crate) fn new<T: OnUpgrade>(on_upgrade: T) -> Self {
        let mut on_upgrade = Some(on_upgrade);
        OnUpgradeObj(Box::new(move |io| {
            let on_upgrade = on_upgrade.take().unwrap();
            on_upgrade.on_upgrade(io)
        }))
    }

    pub(crate) fn upgrade(
        mut self,
        io: Upgraded,
    ) -> Box<dyn Future<Item = (), Error = ()> + Send + 'static> {
        (self.0)(io)
    }
}
